"""Phase 2: add fixtures table

Revision ID: 0e35621fe635
Revises: e8be6b7b1373
Create Date: 2026-05-15 20:35:45.864157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e35621fe635'
down_revision = 'e8be6b7b1373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_code', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_type_code', sa.String(length=16), nullable=False),
    sa.Column('set_no', sa.Integer(), nullable=False),
    sa.Column('current_version_code', sa.String(length=8), nullable=False),
    sa.Column('current_status', sa.String(length=16), nullable=False),
    sa.Column('parent_fixture_id', sa.BigInteger(), nullable=True),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('planned_arrival_date', sa.Date(), nullable=True),
    sa.Column('is_sealed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sealed_at', sa.DateTime(), nullable=True),
    sa.Column('sealed_by', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sealed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.create_index('idx_batch', ['batch_id'], unique=False)
        batch_op.create_index('idx_parent', ['parent_fixture_id'], unique=False)
        batch_op.create_index('idx_project', ['project_id'], unique=False)
        batch_op.create_index('idx_status', ['current_status'], unique=False)
        batch_op.create_index('idx_type', ['fixture_type_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_index('idx_type')
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_project')
        batch_op.drop_index('idx_parent')
        batch_op.drop_index('idx_batch')

    op.drop_table('fixtures')
    # ### end Alembic commands ###
