"""Phase 1: add fixture_template_snapshots table

Revision ID: 1a6913de1eac
Revises: 7e80a54571fd
Create Date: 2026-05-13 15:05:28.746124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6913de1eac'
down_revision = '7e80a54571fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_template_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('source_template_id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_type_code', sa.String(length=32), nullable=False),
    sa.Column('product_type', sa.String(length=16), nullable=False),
    sa.Column('default_lt_days', sa.Integer(), nullable=True),
    sa.Column('default_iqc_interval_days', sa.Integer(), nullable=True),
    sa.Column('default_install_interval_days', sa.Integer(), nullable=True),
    sa.Column('default_acceptance_interval_days', sa.Integer(), nullable=True),
    sa.Column('default_handover_interval_days', sa.Integer(), nullable=True),
    sa.Column('default_maintenance_threshold', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('synced_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_template_id'], ['fixture_templates.id'], ),
    sa.ForeignKeyConstraint(['synced_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'fixture_type_code', name='uk_project_type'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('fixture_template_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_project', ['project_id'], unique=False)
        batch_op.create_index('idx_source_template', ['source_template_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture_template_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_source_template')
        batch_op.drop_index('idx_project')

    op.drop_table('fixture_template_snapshots')
    # ### end Alembic commands ###
