"""Phase 2: add audit_logs table

Revision ID: 3cf8a913acea
Revises: f606ac693c26
Create Date: 2026-05-15 20:57:22.178227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf8a913acea'
down_revision = 'f606ac693c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_table', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_action', ['action'], unique=False)
        batch_op.create_index('idx_created', ['created_at'], unique=False)
        batch_op.create_index('idx_operator', ['operator_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_operator')
        batch_op.drop_index('idx_created')
        batch_op.drop_index('idx_action')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
