"""Phase 3: add self-ref FK fk_drawings_source

Revision ID: 74c24e756ba1
Revises: 924cd214eb0d
Create Date: 2026-05-17 11:01:56.570196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c24e756ba1'
down_revision = '924cd214eb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_drawings_source', 'drawings', ['source_drawing_id'], ['id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_drawings_source', type_='foreignkey')

    # ### end Alembic commands ###
