"""Phase 1: add projects table

Revision ID: 7e80a54571fd
Revises: 24fbd93c72dc
Create Date: 2026-05-12 16:27:42.974709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e80a54571fd'
down_revision = '24fbd93c72dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_code', sa.String(length=10), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('product_type', sa.Enum('SUS_VC', 'CU_VC', 'HP'), nullable=False),
    sa.Column('project_owner_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_owner', ['project_owner_id'], unique=False)
        batch_op.create_index('idx_product_type', ['product_type'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_product_type')
        batch_op.drop_index('idx_owner')

    op.drop_table('projects')
    # ### end Alembic commands ###
