"""Phase 3: add drawings and purchase_requisitions tables

Revision ID: 924cd214eb0d
Revises: 9cfc47ae4fd0
Create Date: 2026-05-17 10:58:02.735420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924cd214eb0d'
down_revision = '9cfc47ae4fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False, comment='关联治具 ID'),
    sa.Column('version_code', sa.String(length=8), nullable=False, comment='图纸版本号，对应 fixture.current_version_code（如 A1、A2）'),
    sa.Column('drawing_type', sa.String(length=16), nullable=False, comment='图纸类型：design_drawing（设计图纸）/ dfm_report（DFM 报告）'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='文件相对路径（正斜杠，由 utils/upload.py:save_upload 返回）'),
    sa.Column('acceptance_standard', sa.Text(), nullable=True, comment='关键尺寸 / 验收标准文字描述（主要用于 design_drawing）'),
    sa.Column('bom_info', sa.Text(), nullable=True, comment='BOM 信息（主要用于 design_drawing）'),
    sa.Column('is_copied', sa.Boolean(), nullable=False, comment='是否复制既有图纸（简化流程标记）'),
    sa.Column('source_drawing_id', sa.BigInteger(), nullable=True, comment='复制来源图纸 ID（is_copied=True 时填写）'),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=False, comment='上传者 user_id'),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True, comment='PM 确认人 user_id'),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True, comment='PM 确认时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_drawing_id'], ['drawings.id'], name='fk_drawings_source', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.create_index('idx_drawings_fixture', ['fixture_id'], unique=False)
        batch_op.create_index('idx_drawings_type', ['drawing_type'], unique=False)
        batch_op.create_index('idx_drawings_version', ['version_code'], unique=False)

    op.create_table('purchase_requisitions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False, comment='关联治具 ID'),
    sa.Column('requisition_no', sa.String(length=32), nullable=False, comment='采购申请单号，由 purchase_requisition_service 生成'),
    sa.Column('drawing_id', sa.BigInteger(), nullable=True, comment='关联图纸 ID（选填）'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='申请数量，须 ≥ 1'),
    sa.Column('spec_note', sa.Text(), nullable=True, comment='规格说明 / 技术要求'),
    sa.Column('required_date', sa.Date(), nullable=True, comment='要求到货日期'),
    sa.Column('confirm_status', sa.String(length=16), nullable=False, comment='PM 确认状态：pending（待确认）/ confirmed（已确认）'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='申请发起人 user_id'),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True, comment='PM 确认人 user_id'),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True, comment='PM 确认时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisition_no'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('purchase_requisitions', schema=None) as batch_op:
        batch_op.create_index('idx_pr_fixture', ['fixture_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_requisitions', schema=None) as batch_op:
        batch_op.drop_index('idx_pr_fixture')

    op.drop_table('purchase_requisitions')
    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.drop_index('idx_drawings_version')
        batch_op.drop_index('idx_drawings_type')
        batch_op.drop_index('idx_drawings_fixture')

    op.drop_table('drawings')
    # ### end Alembic commands ###
