"""fix status_history from_status to_status VARCHAR 16 to 32

Revision ID: 9cfc47ae4fd0
Revises: de2a67838513
Create Date: 2026-05-16 08:41:28.640447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cfc47ae4fd0'
down_revision = 'de2a67838513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture_status_history', schema=None) as batch_op:
        batch_op.alter_column('from_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('to_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture_status_history', schema=None) as batch_op:
        batch_op.alter_column('to_status',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               existing_nullable=False)
        batch_op.alter_column('from_status',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               existing_nullable=True)

    # ### end Alembic commands ###
