"""Phase 3: add goods_receipts, iqc_reports, emergency_auth_records

Revision ID: bf7cdd51266e
Revises: dc71e3fd1b7d
Create Date: 2026-05-17 17:18:06.236943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7cdd51266e'
down_revision = 'dc71e3fd1b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_receipts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False, comment='关联治具 ID'),
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=True, comment='关联 PO ID（可选）'),
    sa.Column('actual_arrival_date', sa.Date(), nullable=False, comment='实际到货日期'),
    sa.Column('received_qty', sa.Integer(), nullable=False, comment='签收数量'),
    sa.Column('received_by', sa.BigInteger(), nullable=False, comment='签收人 user_id'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('goods_receipts', schema=None) as batch_op:
        batch_op.create_index('idx_goods_receipts_fixture', ['fixture_id'], unique=False)

    op.create_table('iqc_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False, comment='关联治具 ID'),
    sa.Column('result', sa.String(length=16), nullable=False, comment='检验结果：pass / fail / concession'),
    sa.Column('inspector_id', sa.BigInteger(), nullable=False, comment='检验员 user_id'),
    sa.Column('inspection_date', sa.DateTime(), nullable=False, comment='检验日期时间'),
    sa.Column('defect_description', sa.Text(), nullable=True, comment='缺陷描述（result=fail 时建议填写）'),
    sa.Column('file_path', sa.String(length=512), nullable=True, comment='检验报告附件相对路径（正斜杠，由 utils/upload.py:save_upload 返回）'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('iqc_reports', schema=None) as batch_op:
        batch_op.create_index('idx_iqc_reports_fixture', ['fixture_id'], unique=False)
        batch_op.create_index('idx_iqc_reports_result', ['result'], unique=False)

    op.create_table('emergency_auth_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False, comment='关联治具 ID'),
    sa.Column('iqc_report_id', sa.BigInteger(), nullable=False, comment='触发本授权的 IQC 报告 ID'),
    sa.Column('authorized_by_pm', sa.BigInteger(), nullable=False, comment='PM 授权人 user_id'),
    sa.Column('authorized_by_iqc', sa.BigInteger(), nullable=False, comment='IQC 授权人 user_id'),
    sa.Column('authorization_date', sa.DateTime(), nullable=False, comment='授权日期时间'),
    sa.Column('risk_description', sa.Text(), nullable=False, comment='风险说明，不得为空'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['authorized_by_iqc'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['authorized_by_pm'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['iqc_report_id'], ['iqc_reports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('emergency_auth_records', schema=None) as batch_op:
        batch_op.create_index('idx_emergency_auth_fixture', ['fixture_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_auth_records', schema=None) as batch_op:
        batch_op.drop_index('idx_emergency_auth_fixture')

    op.drop_table('emergency_auth_records')
    with op.batch_alter_table('iqc_reports', schema=None) as batch_op:
        batch_op.drop_index('idx_iqc_reports_result')
        batch_op.drop_index('idx_iqc_reports_fixture')

    op.drop_table('iqc_reports')
    with op.batch_alter_table('goods_receipts', schema=None) as batch_op:
        batch_op.drop_index('idx_goods_receipts_fixture')

    op.drop_table('goods_receipts')
    # ### end Alembic commands ###
