"""Phase 3: add purchase_orders and purchase_order_items tables

Revision ID: dc71e3fd1b7d
Revises: 74c24e756ba1
Create Date: 2026-05-17 15:08:11.809094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc71e3fd1b7d'
down_revision = '74c24e756ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('po_no', sa.String(length=32), nullable=False, comment='PO 单号，由 purchase_order_service 生成'),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False, comment='供应商'),
    sa.Column('contract_no', sa.String(length=64), nullable=True, comment='合同号（选填）'),
    sa.Column('order_date', sa.Date(), nullable=False, comment='采购下单日期（Q-012：Phase 3 仅存下单日，计划日期推算留 Phase 5）'),
    sa.Column('total_lead_time_days', sa.Integer(), nullable=True, comment='总交期（天数，选填）'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='合同总金额（元）；成本字段，查看权限控制留 Service'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：open（进行中）/ closed（已结案）/ cancelled（已作废）'),
    sa.Column('cancel_reason', sa.String(length=256), nullable=True, comment='作废原因'),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True, comment='作废时间'),
    sa.Column('cancelled_by', sa.BigInteger(), nullable=True, comment='作废操作人 user_id'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='创建人 user_id'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后更新时间'),
    sa.Column('version', sa.Integer(), nullable=False, comment='乐观锁版本号（手动校验，严禁 __mapper_args__ version_id_col）'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_no'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index('idx_po_order_date', ['order_date'], unique=False)
        batch_op.create_index('idx_po_status', ['status'], unique=False)
        batch_op.create_index('idx_po_supplier', ['supplier_id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False, comment='所属 PO'),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False, comment='关联治具（一 item 一治具）'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='单价（元）；成本字段，查看权限控制留 Service'),
    sa.Column('item_lead_time_days', sa.Integer(), nullable=True, comment='本明细项交期（天数，选填）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index('idx_poi_fixture', ['fixture_id'], unique=False)
        batch_op.create_index('idx_poi_po', ['purchase_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index('idx_poi_po')
        batch_op.drop_index('idx_poi_fixture')

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index('idx_po_supplier')
        batch_op.drop_index('idx_po_status')
        batch_op.drop_index('idx_po_order_date')

    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
