"""fix current_status VARCHAR 16 to 32

Revision ID: de2a67838513
Revises: 3cf8a913acea
Create Date: 2026-05-16 08:40:36.088422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de2a67838513'
down_revision = '3cf8a913acea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.alter_column('current_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.alter_column('current_status',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
