"""Phase 2: add fixture_status_history table

Revision ID: f606ac693c26
Revises: 0e35621fe635
Create Date: 2026-05-15 20:46:24.332876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f606ac693c26'
down_revision = '0e35621fe635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('related_table', sa.String(length=64), nullable=True),
    sa.Column('related_id', sa.BigInteger(), nullable=True),
    sa.Column('operator_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('fixture_status_history', schema=None) as batch_op:
        batch_op.create_index('idx_created', ['created_at'], unique=False)
        batch_op.create_index('idx_fixture', ['fixture_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture_status_history', schema=None) as batch_op:
        batch_op.drop_index('idx_fixture')
        batch_op.drop_index('idx_created')

    op.drop_table('fixture_status_history')
    # ### end Alembic commands ###
